// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: token.sql

package database

import (
	"context"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (token, created_at, updated_at, user_id)
VALUES (
    $1, NOW(), NOW(), $2
)
`

type CreateRefreshTokenParams struct {
	Token  string
	UserID string
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken, arg.Token, arg.UserID)
	return err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshToken, token)
	return err
}

const getUserIDFromRefreshToken = `-- name: GetUserIDFromRefreshToken :one
SELECT user_id from refresh_tokens
WHERE token = $1
`

func (q *Queries) GetUserIDFromRefreshToken(ctx context.Context, token string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserIDFromRefreshToken, token)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}
