// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package database

import (
	"context"
	"time"
)

const changeDetail = `-- name: ChangeDetail :exec
UPDATE users
SET email = $1, hashed_password = $2, updated_at = NOW()
WHERE id = $3
`

type ChangeDetailParams struct {
	Email          string
	HashedPassword string
	ID             string
}

func (q *Queries) ChangeDetail(ctx context.Context, arg ChangeDetailParams) error {
	_, err := q.db.ExecContext(ctx, changeDetail, arg.Email, arg.HashedPassword, arg.ID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email, hashed_password)
VALUES (
    gen_random_uuid(), NOW(), NOW(), $1, $2
)
RETURNING id, created_at, updated_at, email, hashed_password
`

type CreateUserParams struct {
	Email          string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}

const deleteUsers = `-- name: DeleteUsers :exec
DELETE FROM users
`

func (q *Queries) DeleteUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUsers)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, created_at, updated_at, email FROM users
WHERE email = $1 AND hashed_password = $2
`

type GetUserParams struct {
	Email          string
	HashedPassword string
}

type GetUserRow struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, arg.Email, arg.HashedPassword)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID    string
	Email string
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const getUserPassword = `-- name: GetUserPassword :one
SELECT hashed_password FROM users
WHERE email = $1
`

func (q *Queries) GetUserPassword(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserPassword, email)
	var hashed_password string
	err := row.Scan(&hashed_password)
	return hashed_password, err
}
