// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhook.sql

package database

import (
	"context"
)

const updateRed = `-- name: UpdateRed :exec
UPDATE users set is_chirpy_red = TRUE
WHERE id = $1
`

func (q *Queries) UpdateRed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateRed, id)
	return err
}
